version: '3.8'

services:
  flask-app:
    image: flask
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "8080:8080"
    networks:
      - wasmiot-net
    environment:
      - PYTHONUNBUFFERED=1

networks:
  wasmiot-net:
    external: true