[package]
name = "spectral_analysis"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
rustfft = "6"

[profile.release]
opt-level = "z"
strip = true
lto = "fat"
codegen-units = 1