[package]
name = "wasi_mobilenet_onnx"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wit-bindgen = "0.12.0"
tract-onnx = "0.21.7"
image = "0.24.7"
time = "0.3.35"

[lib]
crate-type = ["cdylib"]
